#! /bin/sh
#######################################################
##                                                   ##
##  ______  ___________ _    ____  ________  _____   ##
##  | ___ \/  ___| ___ \ |  | |  \/  | ___ \/  __ \  ##
##  | |_/ /\ `--.| |_/ / |  | | .  . | |_/ /| /  \/  ##
##  | ___ \ `--. \  __/| |/\| | |\/| |    / | |      ##
##  | |_/ //\__/ / |   \  /\  / |  | | |\ \ | \__/\  ##
##  \____/ \____/\_|    \/  \/\_|  |_|_| \_| \____/  ##
##   By:Sigladon                                     ## 
##                                                   ##
#######################################################
#esto es una prueba


pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
picom -f &
~/.config/polybar/launch.sh --hack
xrandr --output DVI-I-1 --primary --mode 1600x900 --rotate normal 
bspc monitor DVI-I-1 -d I II III IV V VI VII VIII IX X

bspc config border_width                      3
bspc config window_gap                        4
bspc config top_padding                       25
bspc config bottom_padding                    5
bspc config left_padding                      5
bspc config right_padding                     5


bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config pointer_follows_focus             false
bspc config focus_follows_pointer             true

# BSPWM coloring
bspc config normal_border_color               "#727072"
bspc config active_border_color               "#0a141e"
bspc config focused_border_color              "#1a4775"
bspc config presel_feedback_color             "#ff9e64"

# Rules
bspc rule --add *:microsoft-edge desktop='^6'
bspc rule --add *:music.youtube.com desktop='^10'
bspc rule -a Alacritty desktop=^1
bspc rule -a vlc desktop=^8*: 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
nitrogen --restore &

