local o = vim.o
local wo = vim.wo

o.autoindent = true
o.copyindent = true
o.background = "dark"
o.backup = false
o.clipboard = "unnamedplus"
o.cmdheight = 4
--o.cursorline = true
--o.cursorlineopt = "number"
o.encoding = "UTF-8"
o.expandtab = true
o.hidden = true
o.laststatus = 0
o.mouse = "a"
o.showmode = false
o.wrap = true
o.ruler = true
o.tabstop = 2
o.number = true
o.relativenumber = true
o.showmode = true
