colors:
  primary:
    background: '#030B17'
    foreground: '#F0F0F0'
  normal:
    black:   '#05172E'
    red:     '#E60049'
    green:   '#0CEB77'
    yellow:  '#E2E600'
    blue:    '#E65000'
    magenta: '#5000E6'
    cyan:    '#0095E6'
    white:   '#E1EDFC'
  bright:
    black:   '#0F4386'
    red:     '#FF3776'
    green:   '#4BF69D'
    yellow:  '#FCFF37'
    blue:    '#FF7D37'
    magenta: '#7D37FF'
    cyan:    '#37B9FF'
    white:   '#EBF3FD'

